name: 'Build and test'

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v3

      - name: "Install packages"
        run: |
          npm install          

      - name: "Execute tests"
        run: |
          npm run test
